### ISSUE TITLE
是否可以增加华为云dns地域分组

### ISSUE THREAD

**Issue by ghost** [KincaidYang/CNAMEFlattening#9]
是否可以增加华为云dns地域分组

您好。我看到华为云云dns中，cname拉平仅限国内运营商线路。是否可以增加一下海外地区的拉平（比如亚太地区、欧洲地区什么的），

**Comment by KincaidYang** [comment]
需要精确到大洲还是国家？

**Comment by KincaidYang** [comment]
我这周末抽时间弄一下吧

**Comment by ghost** [comment]
大洲即可，非常感谢。（因为对于中国云服务的cdn，基本都是大洲区分海外）
真的非常感谢您的回复。

**Comment by ghost** [comment]
或者我有一个提议，就是先拉平到大洲，再对主要国家进行拉平（因为华为云大洲里面真的非常多国家），这样既能加速海外地区访问，又能有效精准加速

**Comment by ghost** [comment]
您好我看了一下，应该看懂了可以自己整了，所以先关issue了，辛苦
